#pragma once

#include <stdint.h>

#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/usart.h>

#define BOARD_AXIS_COUNT 4U

#define BOARD_STEP_PORT GPIOA
#define BOARD_STEP_PIN_X GPIO0
#define BOARD_STEP_PIN_Y GPIO1
#define BOARD_STEP_PIN_Z GPIO2
#define BOARD_STEP_PIN_A GPIO3

#define BOARD_DIR_PORT GPIOA
#define BOARD_DIR_PIN_X GPIO4
#define BOARD_DIR_PIN_Y GPIO5
#define BOARD_DIR_PIN_Z GPIO6
#define BOARD_DIR_PIN_A GPIO7

#define BOARD_DRV_EN_PORT GPIOB
#define BOARD_DRV_EN_PIN GPIO0
#define BOARD_DRV_EN_ACTIVE_LOW 1U

#define BOARD_USART USART1
#define BOARD_USART_RCC RCC_USART1
#define BOARD_USART_GPIO_PORT GPIOA
#define BOARD_USART_TX_PIN GPIO9
#define BOARD_USART_RX_PIN GPIO10
#define BOARD_USART_AF GPIO_AF7

#define BOARD_INPUT_PORT GPIOC
#define BOARD_INPUT_ESTOP_PIN GPIO13
#define BOARD_INPUT_LIMIT_X_PIN GPIO0
#define BOARD_INPUT_LIMIT_Y_PIN GPIO1
#define BOARD_INPUT_LIMIT_Z_PIN GPIO2
#define BOARD_INPUT_HAND_PIN GPIO3

#define BOARD_STEP_TIMER TIM6
#define BOARD_STEP_TIMER_RCC RCC_TIM6
#define BOARD_STEP_TIMER_IRQ NVIC_TIM6_DAC_IRQ

#define BOARD_STEP_TICK_HZ 25000U

enum {
    BOARD_INPUT_BIT_LIMIT_X = (1u << 0),
    BOARD_INPUT_BIT_LIMIT_Y = (1u << 1),
    BOARD_INPUT_BIT_LIMIT_Z = (1u << 2),
    BOARD_INPUT_BIT_ESTOP = (1u << 3),
    BOARD_INPUT_BIT_HAND = (1u << 4)
};
